services:

  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - nodeapp
    networks:
      - backend

  nodeapp:
    build: ./app
    container_name: node_server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan/work
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
